plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/eliottpro/Desktop/ATLAS"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
X-Robots-Tag = "noindex, nofollow"